services:
  mongodb:
    image: mongo:5.0.15
    command: mongod
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: coffee-shop
    #   MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

    # docker compose -p coffee-shop-mongodb up -d
